services:
    hostmanager:
        image: dkarlovi/docker-hostmanager:latest
        profiles:
            - linux
        restart: always
        volumes:
            - /etc/hosts:/hosts
            - /var/run/docker.sock:/var/run/docker.sock
